### ISSUE TITLE
error loading homepage

### ISSUE THREAD

**Issue by mamema** [mauriceoegerli/viewtube-vue#923]
### Describe the Bug
using latest dev container with this vars configured:

VIEWTUBE_API_URL
VIEWTUBE_REDIS_HOST
VIEWTUBE_REDIS_PORT
VIEWTUBE_REDIS_PASSWORD
VIEWTUBE_DATABASE_HOST
VIEWTUBE_ALLOWED_DOMAIN
VIEWTUBE_PRIVATE_VAPID

launching the base url viewtube.example.com

leads to an mainly empty page. no video tumbnails and the error displaying "error loading homepage" - refresh to try again

Refresh doesn't help

Entering something into the search bar leads to the needed entries

### Expected Behaviour
viewtube should come up with the usual video thumbnails

### Device Info 

- Device: Mac
- OS: [e.g. OSX big dur
- Browser: Chrome/Safari
- Version: latest

### Additional Context
running behind reverse proxy: haproxy

**Comment by moisout** [comment]
If you try opening viewtube.example.com/api/ (replace with your domain) in a browser, does it return anything?

**Comment by mamema** [comment]
yes, everything looks good. Swagger explore bar, with my http domain https://example.com/api/json address in

**Comment by moisout** [comment]
Can you check the logs
`docker logs <your-container-name>`
 the important message is this one:
![image](https://user-images.githubusercontent.com/15955392/134773102-9d712270-dac5-4ac2-ad66-77f65b8be70a.png)
`refreshing popular page`
Does that one show up for you?

**Comment by mamema** [comment]
yes,

ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ready Server listening on http://localhost:8066
ℹ Refreshing popular page
ℹ Modern bundles are detected. Modern mode (server) is enabled now.

**Comment by moisout** [comment]
If you open any other page (for example a video) and refresh the browser with f5, does it work?

**Comment by mamema** [comment]
No, but the situation changes a bit.
if i search a video in the search bar, play this video, press f5 then

the page refreshes and comes back without the "popular videos" line and black empty page.
the https line is then https://example.com/results
If i then type something in the searchbar, no search results are coming back.
the https line is then https://example.com/results?search_query=Wathever

if have to shorten the https line manually to https again://example.com to get search results again.

**Comment by moisout** [comment]
That is very weird behavior. Are there any errors in the log on the browser or on the server?

**Comment by mamema** [comment]
client - yes, firefox browser: after F5 DOMException: Node.appendChild: Cannot add children to a Comment
(500
Internal Server Error), when F5 is pressed while watching something. No Browser error on the topic "error loading homepage"
server - 
WARN  Cannot stringify a function transformRequest
WARN  Cannot stringify a function transformResponse
WARN  Cannot stringify a function httpAdapter

**Comment by chazy-chaz** [comment]
Hi
I have the same problem too.
docker and nginx reverse proxy

**Comment by Stolz** [comment]
Same problem here with Docker. https://viewtube.example.com takes 3 minutes to load and eventually shows 

>  Error loading homepage. Refresh the page to try again

Browser's console does not show any error and https://viewtube.example.com/api works fine. I can see Swagger UI and interact with the API endpoints.

My Docker config:

    version: '3'
    
    services:
    
      viewTube:
        container_name: viewtube
        environment:
          VIEWTUBE_ALLOWED_DOMAIN: '/example\.com$$/'
          VIEWTUBE_API_URL: https://viewtube.example.com/api/
          VIEWTUBE_CURRENT_DOMAIN: viewtube.example.com
          VIEWTUBE_DATABASE_HOST: mongo
          VIEWTUBE_DATABASE_PASSWORD: $VIEWTUBE_DATABASE_PASSWORD
          VIEWTUBE_DATABASE_USER: viewtube
          VIEWTUBE_JWT_SECRET: $VIEWTUBE_JWT_SECRET
          VIEWTUBE_PRIVATE_VAPID: $VIEWTUBE_PRIVATE_VAPID
          VIEWTUBE_PUBLIC_VAPID: $VIEWTUBE_PUBLIC_VAPID
          VIEWTUBE_REDIS_HOST: redis
          VIEWTUBE_YOUTUBE_COOKIE: $VIEWTUBE_YOUTUBE_COOKIE
          VIEWTUBE_YOUTUBE_IDENTIFIER: $VIEWTUBE_YOUTUBE_IDENTIFIER
        hostname: viewtube
        image: mauriceo/viewtube:latest
        labels:
          - traefik.enable=true
          - traefik.http.services.viewtube.loadbalancer.server.port=8066
        networks:
          - proxy
        restart: unless-stopped
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./data:/data
    
    networks:
    
      proxy:
        external: true
Logs:

	--- Environment variables ---

	~ Used default value for the following environment variables
	PORT:                           8066
	VIEWTUBE_DATABASE_PORT:         27017
	VIEWTUBE_REDIS_PORT:            6379
	VIEWTUBE_REDIS_PASSWORD:        empty
	VIEWTUBE_JWT_EXPIRATION_TIME:   43200
	VIEWTUBE_DATA_DIRECTORY:        /data

	✓ Found values for the following environment variables
	VIEWTUBE_JWT_SECRET:            *****
	VIEWTUBE_PUBLIC_VAPID:          redacted
	VIEWTUBE_PRIVATE_VAPID:         *****
	VIEWTUBE_CURRENT_DOMAIN:        viewtube.example.com
	VIEWTUBE_API_URL:               https://viewtube.example.com/api/
	VIEWTUBE_DATABASE_HOST:         mongo
	VIEWTUBE_DATABASE_USER:         viewtube
	VIEWTUBE_DATABASE_PASSWORD:     *****
	VIEWTUBE_REDIS_HOST:            redis
	VIEWTUBE_ALLOWED_DOMAIN:        /example\.com$/
	VIEWTUBE_YOUTUBE_COOKIE:        redacted
	VIEWTUBE_YOUTUBE_IDENTIFIER:    redacted
	ℹ Primary node started: pid 1
	ℹ Worker node started: pid 23
	ℹ Worker node started: pid 15
	ℹ Worker node started: pid 30
	ℹ Worker node started: pid 21
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(Use `node --trace-warnings ...` to show where the warning was created)
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(Use `node --trace-warnings ...` to show where the warning was created)
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(Use `node --trace-warnings ...` to show where the warning was created)
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(Use `node --trace-warnings ...` to show where the warning was created)
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:23) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:15) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:30) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	(node:21) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
	ℹ Modern bundles are detected. Modern mode (server) is enabled now.
	ℹ Modern bundles are detected. Modern mode (server) is enabled now.
	ℹ Modern bundles are detected. Modern mode (server) is enabled now.
	ℹ Modern bundles are detected. Modern mode (server) is enabled now.
	ready Server listening on http://localhost:8066
	ℹ Refreshing popular page

**Comment by moisout** [comment]
Thank you very much for posting this! I will try to reproduce the problem, and see if i can find a fix.

**Comment by kylejwatson** [comment]
Let me know if this should be created as a separate issue but I was getting similar errors when failing to refresh my subscriptions page (was returning old results but stating last refresh a few weeks old).

I restarted my Redis service and that seemed to fix it.

Here's the logs of when I was loading the subscriptions page:
```
Oct 26 19:50:32 hostname node[24663]:  ERR Error running script (call to f_ff9c18634832b0b4115a19b4de5f4788a7cfbd4e): @use
Oct 26 19:50:32 hostname node[24663]:   at parseError (node_modules/redis-parser/lib/parser.js:179:12)
Oct 26 19:50:32 hostname node[24663]:   at parseType (node_modules/redis-parser/lib/parser.js:302:14)
Oct 26 19:50:49 hostname node[24663]:  WARN  Cannot stringify a function transformRequest
Oct 26 19:50:49 hostname node[24663]:  WARN  Cannot stringify a function transformResponse
Oct 26 19:50:49 hostname node[24663]:  WARN  Cannot stringify a function httpAdapter
Oct 26 19:50:49 hostname node[24663]:  WARN  Cannot stringify a function validateStatus
```
After restarting Redis and refreshing the subscription page it has the latest videos and last refresh is set to now:
```
Oct 26 20:00:03 hostname node[24663]: Starting subscriptions job 409 at 2021-10-26 18:00:03.748Z
Oct 26 20:00:03 hostname node[24663]: Subscriptions job: 0% done
Oct 26 20:00:05 hostname node[24663]: Subscriptions job: 50% done
Oct 26 20:00:08 hostname node[24663]: Done at 2021-10-26 18:00:06.170Z: 159 channels, 2312 videos
```

**Comment by moisout** [comment]
Hi! I have pushed a new update to the development branch (available on docker as the :dev tag). It should hopefully fix the issues here.

You now **don't** need the following environment variables anymore, you can delete them:
VIEWTUBE_API_URL
VIEWTUBE_DOMAIN
VIEWTUBE_PRIVATE_VAPID
VIEWTUBE_PUBLIC_VAPID
VIEWTUBE_JWT_SECRET

You only need the following new one:
VIEWTUBE_URL

Which needs to be the url you're accessing viewtube from, including the scheme (http or https)
Example 1: 
local ip adress and port 8066
VIEWTUBE_URL=http://123.23.0.3:8066
Example 2:
Behind a reverse proxy using a domain with ssl
VIEWTUBE_URL=https://viewtube.example.com

I will update the documentation, but have posted this here first so the people having issues can see it!

**Comment by Stolz** [comment]
Thanks for the update @mauriceoegerli 

In my case the `dev` build help a bit but I still experience issues. I removed the ENV vars in favor of VIEWTUBE_URL. Now the container takes 30 seconds to start instead of 3 minutes, but according to Docker it remains as 'unhealthy' and it takes 30 seconds to get any response from port 8066:

```
ℹ Primary node started: pid 1
ℹ Worker node started: pid 27
ℹ Worker node started: pid 21
ℹ Worker node started: pid 29
start Starting in clustered mode
ℹ Worker node started: pid 15
 WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
 WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
 WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
 WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
 WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
 WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
 WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
 WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
 WARN  Silently ignoring module as programatic usage detected.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ready Server listening on http://0.0.0.0:8066
ℹ Refreshing popular page
ℹ Refreshed popular page
```
If you wait long enough everything seems to work. I managed to create a user and import my subscriptions but having to wait 30 seconds for every action on the page makes it unusable. I guess under the hood there are some synchronous network requests that are timing out but I don't see any error in the logs

```
docker exec -it viewtube wget http://localhost:8066/
Connecting to localhost:8066 (127.0.0.1:8066)
saving to 'index.html'
index.html           100% |********************************************************************************************************************************************| 48918  0:00:00 ETA
'index.html' saved
Command exited with non-zero status 1
real    0m 30.30s
user    0m 0.00s
sys     0m 0.00s
```

**Comment by moisout** [comment]
> Thanks for the update @mauriceoegerli 
> 
> In my case the `dev` build help a bit but I still experience issues. I removed the ENV vars in favor of VIEWTUBE_URL. Now the container takes 30 seconds to start instead of 3 minutes, but according to Docker it remains as 'unhealthy' and it takes 30 seconds to get any response from port 8066:
> 
> ```
> ℹ Primary node started: pid 1
> ℹ Worker node started: pid 27
> ℹ Worker node started: pid 21
> ℹ Worker node started: pid 29
> start Starting in clustered mode
> ℹ Worker node started: pid 15
>  WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
>  WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
>  WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
>  WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
> ℹ Modern bundles are detected. Modern mode (server) is enabled now.
>  WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
>  WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
> ℹ Modern bundles are detected. Modern mode (server) is enabled now.
> ℹ Modern bundles are detected. Modern mode (server) is enabled now.
>  WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
>  WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.
>  WARN  Silently ignoring module as programatic usage detected.
> ℹ Modern bundles are detected. Modern mode (server) is enabled now.
> ready Server listening on http://0.0.0.0:8066
> ℹ Refreshing popular page
> ℹ Refreshed popular page
> ```
> If you wait long enough everything seems to work. I managed to create a user and import my subscriptions but having to wait 30 seconds for every action on the page makes it unusable. I guess under the hood there are some synchronous network requests that are timing out but I don't see any error in the logs
> 
> ```
> docker exec -it viewtube wget http://localhost:8066/
> Connecting to localhost:8066 (127.0.0.1:8066)
> saving to 'index.html'
> index.html           100% |********************************************************************************************************************************************| 48918  0:00:00 ETA
> 'index.html' saved
> Command exited with non-zero status 1
> real    0m 30.30s
> user    0m 0.00s
> sys     0m 0.00s
> ```
> 

I have tried, but i can't reproduce this. Have you made sure the VIEWTUBE_URL matches the url you're accessing it from exactly?

**Comment by mamema** [comment]
my problem, using the latest dev build is, that the communication with the mong-db container fails:

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new HostAddress (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/utils.js:1041:36)
    at fromString (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/utils.js:1085:16)
    at Array.map (<anonymous>)
    at Object.parseOptions (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/connection_string.js:214:45)
    at new MongoClient (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/mongo_client.js:62:46)
    at /home/app/.yarn/cache/mongoose-npm-6.0.8-252eba2eae-3d2ad342d6.zip/node_modules/mongoose/lib/connection.js:779:16
    at new Promise (<anonymous>) {
  input: 'mongodb://192.168.0.30:27017:27017',

in the viewtube container the env var set is:
VIEWTUBE_DATABASE_HOST=192.168.0.30:27017

as the viewtube container was connecting in earlier releases and i've nothing changed regarding the database connection, something changed in viewtube.....

**Comment by moisout** [comment]
> my problem, using the latest dev build is, that the communication with the mong-db container fails:
> 
> TypeError [ERR_INVALID_URL]: Invalid URL
>     at new NodeError (node:internal/errors:371:5)
>     at onParseError (node:internal/url:552:9)
>     at new URL (node:internal/url:628:5)
>     at new HostAddress (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/utils.js:1041:36)
>     at fromString (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/utils.js:1085:16)
>     at Array.map (<anonymous>)
>     at Object.parseOptions (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/connection_string.js:214:45)
>     at new MongoClient (/home/app/.yarn/cache/mongodb-npm-4.1.1-b20a26c2b7-242cc95b90.zip/node_modules/mongodb/lib/mongo_client.js:62:46)
>     at /home/app/.yarn/cache/mongoose-npm-6.0.8-252eba2eae-3d2ad342d6.zip/node_modules/mongoose/lib/connection.js:779:16
>     at new Promise (<anonymous>) {
>   input: 'mongodb://192.168.0.30:27017:27017',
> 
> in the viewtube container the env var set is:
> VIEWTUBE_DATABASE_HOST=192.168.0.30:27017
> 
> as the viewtube container was connecting in earlier releases and i've nothing changed regarding the database connection, something changed in viewtube.....
> 
> 
> 
> 

Try specifying the domain and port separately, using the 
VIEWTUBE_DATABASE_PORT

**Comment by mamema** [comment]
that did the trick. Thanks. Working now behind reverse proxy (HAPROXY)

**Comment by moisout** [comment]
I will close this issue now, @Stolz i have created a new one with your issue.
