### ISSUE TITLE
"error loading homepage" and SSL errors

### ISSUE THREAD

**Issue by simphide** [mauriceoegerli/viewtube-vue#931]
### Describe the Bug

Use that docker-compose file (I will change the VAPID keys after the problem is solved):
### Steps to Reproduce the Bug
```
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:latest
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - VIEWTUBE_API_URL=http://10.0.42.12:8066/api/
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_JWT_SECRET=secretscret
      - VIEWTUBE_JWT_EXPIRATION_TIME=43200
      - VIEWTUBE_CURRENT_DOMAIN=http://10.0.42.12:8066/
      - VIEWTUBE_DATA_DIRECTORY=/data
      - VIEWTUBE_PUBLIC_VAPID=BFz-O58uOI24EZhkWifnWwehgdMFoOBu20RLzq-JTaB5PqmdoajmqUwJHEZP671WhvrCl1NN6kvlCBaeYYaEgio
      - VIEWTUBE_PRIVATE_VAPID=a1hBPSWMYvt7dDPQlQoq44gEeXa9wg5KFkxtuF4Dp-Q
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data-db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data-redis:/data

networks:
  viewtube:
```

When you try to open the site it takes really long to load, it says "error loading homepage" and SSL errors occur:
![image](https://user-images.githubusercontent.com/8183517/134773353-d8973b1f-ee4f-4593-a83c-92431ae67b6a.png)

### Expected Behaviour
The site loads properly

### Screenshot/Screen recording
Docker logs:
```
--- Environment variables ---

~ Used default value for the following environment variables

PORT:                           8066
VIEWTUBE_DATABASE_PORT:         27017
VIEWTUBE_DATABASE_USER:         empty
VIEWTUBE_DATABASE_PASSWORD:     empty
VIEWTUBE_REDIS_PORT:            6379
VIEWTUBE_REDIS_PASSWORD:        empty
VIEWTUBE_ALLOWED_DOMAIN:        /^viewtube\.io|\.viewtube\.io$/

✓ Found values for the following environment variables
VIEWTUBE_JWT_SECRET:            *****
VIEWTUBE_PUBLIC_VAPID:          BFz-O58uOI24EZhkWifnWwehgdMFoOBu20RLzq-JTaB5PqmdoajmqUwJHEZP671WhvrCl1NN6kvlCBaeYYaEgio
VIEWTUBE_PRIVATE_VAPID:         *****
VIEWTUBE_CURRENT_DOMAIN:        10.0.42.12:8066
VIEWTUBE_API_URL:               http://10.0.42.12:8066/api/
VIEWTUBE_DATABASE_HOST:         viewtube-mongodb
VIEWTUBE_REDIS_HOST:            viewtube-redis
VIEWTUBE_JWT_EXPIRATION_TIME:   43200
VIEWTUBE_DATA_DIRECTORY:        /data
ℹ Primary node started: pid 1
ℹ Worker node started: pid 22
ℹ Worker node started: pid 15
ℹ Worker node started: pid 21
ℹ Worker node started: pid 34
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ready Server listening on http://localhost:8066
ℹ Refreshing popular page
Starting subscriptions job 1 at 2021-09-25 08:00:00.019Z
Done at 2021-09-25 08:00:00.022Z: 0 channels, 0 videos
Starting subscriptions job 2 at 2021-09-25 09:00:00.009Z
Done at 2021-09-25 09:00:00.010Z: 0 channels, 0 videos
Starting subscriptions job 3 at 2021-09-25 10:00:00.014Z
Done at 2021-09-25 10:00:00.015Z: 0 channels, 0 videos
Starting subscriptions job 4 at 2021-09-25 11:00:00.012Z
Done at 2021-09-25 11:00:00.013Z: 0 channels, 0 videos
Starting subscriptions job 5 at 2021-09-25 12:00:00.020Z
Done at 2021-09-25 12:00:00.021Z: 0 channels, 0 videos
```  
    

### Device Info 

- Device: MacBook
- OS: MacOS 11.0
- Browser: Chrome
- Version: 94.0

### Additional Context
-

**Comment by arjf** [comment]
im having the same issue except my host is debian and my browser is firefox

**Comment by moisout** [comment]
Thanks for reporting! I'll take a look

**Comment by simphide** [comment]
Any news regarding this issue?

**Comment by moisout** [comment]
This seems related to #968 and #923. I am working on a fix to be able to run it on just an ip and port.
I always ran it on a domain through a reverse proxy, so i have never encountered this issue.

**Comment by PascalMinder** [comment]
Any update on the issue?

**Comment by moisout** [comment]
i'm working on it :)

**Comment by moisout** [comment]
Hi! I have pushed a new update to the development branch (available on docker as the :dev tag). It should hopefully fix the issues here.

You now **don't** need the following environment variables anymore, you can delete them:
VIEWTUBE_API_URL
VIEWTUBE_DOMAIN
VIEWTUBE_PRIVATE_VAPID
VIEWTUBE_PUBLIC_VAPID
VIEWTUBE_JWT_SECRET

You only need the following new one:
VIEWTUBE_URL

Which needs to be the url you're accessing viewtube from, including the scheme (http or https)
Example 1: 
local ip adress and port 8066
VIEWTUBE_URL=http://123.23.0.3:8066
Example 2:
Behind a reverse proxy using a domain with ssl
VIEWTUBE_URL=https://viewtube.example.com

I will update the documentation, but have posted this here first so the people having issues can see it!

**Comment by PascalMinder** [comment]
Hi thanks for the update.
I deleted the data folder for the viewtube and the mongoDB container. And recreated the images. The error still persists. 
![image](https://user-images.githubusercontent.com/1893516/140638586-b5eb7f2b-e218-43b1-81d4-7559637e9726.png)
I have recreaded and cleand the redis cache multiple times.
It still wants to load https....

And my docker configuration
![image](https://user-images.githubusercontent.com/1893516/140638871-528c8973-7692-4e54-a876-ca6203377582.png)

Image:
![image](https://user-images.githubusercontent.com/1893516/140642024-35e2a642-2de2-4ada-b69c-34b0b07d6102.png)

**Comment by moisout** [comment]
Hi, thank you for quick answer, i'll try to reproduce your setup and figure out the issue.

**Comment by PascalMinder** [comment]
here part of my docker-compose, might help

```
 redis-viewtube:
    image: redis:6.2.6-alpine
    container_name: redis-viewtube
    restart: unless-stopped
    networks:
      internal:
        aliases:
          - redis-viewtube
  mongodb-viewtube:
    image: mongo:5.0-focal
    container_name: mongodb-viewtube
    restart: unless-stopped
    networks:
      internal:
        aliases:
          - mongo-viewtube
    volumes:
      - "/srv/dev-disk-by-label-volume1/docker/config/mongodb-viewtube/data/db:/data/db"
  viewtube:
    image: mauriceo/viewtube:latest
    container_name: viewtube
    restart: unless-stopped
    networks:
      internal:
        aliases:
          - viewtube
    ports:
      - 8066:8066
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/srv/dev-disk-by-label-volume1/docker/config/viewtube/data:/data"
    environment:
      - PUID=1000
      - PGID=100
      - VIEWTUBE_URL=http://192.168.1.17:8066
      - VIEWTUBE_DATABASE_HOST=mongodb-viewtube
      - VIEWTUBE_REDIS_HOST=redis-viewtube
      - VIEWTUBE_DATA_DIRECTORY=/data
```


A friend of mine uses viewtube behind a nginx proxy and since the update it works for him, but he uses https.

**Comment by FuzzyMistborn** [comment]
Running the :dev tag is improved as I now at least can get the frontend to load.  However, I get no images for the clips and when I click a link to watch a video I get a `ERR_SSL_PROTOCOL_ERROR` which leads me to think it does not like a non-https page.

**Comment by moisout** [comment]
Figured it out! It was the content security policy being too strict. Update coming soon.

**Comment by moisout** [comment]
Update available on the dev tag!

**Comment by PascalMinder** [comment]
hey, looks good I think. I'll play around a bit. Thanks

**Comment by PascalMinder** [comment]
ok, so the start page works now. I created an account and I tried to log in. I get the pop up "welcome xxx" but it seems that the login cookie or something else is not set. When I try to subscribe to a page, the button is greyed out and a message says: please log in:

![image](https://user-images.githubusercontent.com/1893516/140649683-2c06ff36-77e3-4a27-b713-5ad194776c81.png)

**Comment by moisout** [comment]
Thank you for testing. ~~Update is underway.~~ It's up!

**Comment by PascalMinder** [comment]
Very fast :) Thanks. It looks like its working now. I had to refresh the page two or three times till it worked. But it's working now. I also can see my subscription feed.
I look at it more closely later.

**Comment by PascalMinder** [comment]
![image](https://user-images.githubusercontent.com/1893516/140654608-89e1882a-d160-4034-923e-d6a34798df9d.png)

Now, sometimes I am logged in and then if I refresh the page I am logged out. Next refresh I am logged in again. Cookie gets set
![image](https://user-images.githubusercontent.com/1893516/140654629-33928fcc-e718-479a-8a9b-c7d2c2d2c435.png)

**Comment by moisout** [comment]
Can you delete browser data for the page and see if that helps?

**Comment by FuzzyMistborn** [comment]
Seems to be working here.  Not sure these at all are related (so I'm happy to open a separate issue) but 1) i'm seeing a lot of the following errors in my log:

`WARN  Module portal-vue/nuxt not found. Please ensure portal-vue/nuxt is in dependencies and installed.`
`WARN  Module @nuxtjs/axios not found. Please ensure @nuxtjs/axios is in dependencies and installed.`

And 2) HD playback is pretty poor.  As in I have to start playing and pause for a good 5 minutes to get enough of a buffer going to play even at 1080p.

**Comment by moisout** [comment]
Both of those are known, i haven't gotten around to creating an issue for them yet.

#1 is are false warnings, i'll have to figure out how to fix those.

The reason for #2 is that google only lets you stream at a bit above the bandwidth you need, which is too slow for the proxy.

If you want, you can create issues for them!

**Comment by FuzzyMistborn** [comment]
Gotcha on #1.  #2 is interesting, Could of sworn at one point using the viewtube.io instance I was getting 1440p no problem.

**Comment by moisout** [comment]
The fix seems to have worked for people. @simphide, @ajdjyt if you're still running into problems, please open a new issue.
